spring:
  datasource:
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 19801980
    url: jdbc:postgresql://localhost:5432/pharmacy_service?currentSchema=public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9090
springdoc:
  swagger-ui:
    path: /sw
  api-docs:
    path: /sw-doc
#api:
#  info:
#    title: Pharmacy Service API
#    description: powered by Muhammadkomil
#    version: 1.0
#    license-url: nimadir
#    license-name: nimadir
#    contact-email: murodillayevmuhammadkomil@gmail.com
#    contact-url: https://phamacy.uz